"""empty message

Revision ID: 138f9a6c4673
Revises: a1db339b6d4f
Create Date: 2022-07-21 01:12:24.038201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138f9a6c4673'
down_revision = 'a1db339b6d4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
