"""empty message

Revision ID: 69ebef6bbecc
Revises: c4ece1461f0d
Create Date: 2022-07-20 03:44:01.122703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ebef6bbecc'
down_revision = 'c4ece1461f0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
