"""empty message

Revision ID: 879282173c7c
Revises: 
Create Date: 2022-07-18 09:07:32.539598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879282173c7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('authorId',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('authorId',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
