"""empty message

Revision ID: c4ece1461f0d
Revises: 11670071fc2b
Create Date: 2022-07-19 15:27:30.821112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ece1461f0d'
down_revision = '11670071fc2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
